name: llamafactory
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.7.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - av==14.4.0
      - bitsandbytes==0.46.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.6.0
      - decorator==5.2.1
      - deepspeed==0.17.1
      - dill==0.3.8
      - docstring-parser==0.16
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - fastapi==0.115.12
      - ffmpy==0.6.0
      - filelock==3.18.0
      - fire==0.7.0
      - fonttools==4.58.2
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.31.0
      - gradio-client==1.10.1
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.1.3
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.32.4
      - idna==3.10
      - jieba==0.42.1
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - librosa==0.11.0
      - liger-kernel==0.5.10
      - llamafactory==0.9.3.dev0
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - orjson==3.10.18
      - packaging==25.0
      - pandas==2.3.0
      - peft==0.15.2
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pooch==1.8.2
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.0.0
      - rouge-chinese==1.0.3
      - ruff==0.11.13
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - shtab==1.7.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - sse-starlette==2.3.6
      - starlette==0.46.2
      - sympy==1.14.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tomlkit==0.13.3
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - triton==3.3.1
      - trl==0.9.6
      - typer==0.16.0
      - typing-extensions==4.14.0
      - tyro==0.8.14
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.3
      - wandb==0.20.1
      - websockets==15.0.1
      - xxhash==3.5.0
      - yarl==1.20.1
